# _config.yml 基础安全配置
title: 柒柒工坊
description: 工具集合与博客
baseurl: ""
url: "https://Ckreams.github.io"
theme: minima
plugins:
  - jekyll-feed

#关联博客主页面
include: ['_includes']
exclude: ['node_modules']

# 中国访问优化
timezone: Asia/Shanghai
encoding: utf-8

# 加载自定义样式
sass:
  sass_dir: assets/css
  style: compressed
